version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "8883:8883"
      - "9001:9001"
    networks:
      - iot
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./cert/ca-root-cert.crt:/mosquitto/ca-root-cert.crt
      - ./cert/server.key:/mosquitto/server.key
      - ./cert/server.crt:/mosquitto/server.crt

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - iot
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=user
      - DOCKER_INFLUXDB_INIT_PASSWORD=password1234
      - DOCKER_INFLUXDB_INIT_ORG=BRN
      - DOCKER_INFLUXDB_INIT_BUCKET=BLI
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=4eYvsu8wZCJ6tKuE2sxvFHkvYFwSMVK0011hEEiojvejzpSaij86vYQomN_12au6eK-2MZ6Knr-Sax201y70w==
  
  telegraf:
    image: telegraf
    container_name: telegraf
    restart: always
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot

  telegraf2:
    image: telegraf
    container_name: telegraf2
    restart: always
    volumes:
      - ./telegraf2.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot

  telegraf3:
    image: telegraf
    container_name: telegraf3
    restart: always
    volumes:
      - ./telegraf3.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - iot

  telegraf4:
    image: telegraf
    container_name: telegraf4
    restart: always
    volumes:
      - ./telegrafEpic1.conf:/etc/telegraf/telegraf.conf:ro
      - ./cert/magicbit/AmazonRootCA1.pem:/mosquitto/AmazonRootCA1.pem
      - ./cert/magicbit/certificate.pem.crt:/mosquitto/certificate.pem.crt
      - ./cert/magicbit/private.pem.key:/mosquitto/private.pem.key
    depends_on:
      - influxdb
    networks:
      - iot


  telegraf5:
    image: telegraf
    container_name: telegraf5
    restart: always
    volumes:
      - ./telegrafEpic2.conf:/etc/telegraf/telegraf.conf:ro
      - ./cert/magicbit/AmazonRootCA1.pem:/mosquitto/AmazonRootCA1.pem
      - ./cert/magicbit/certificate.pem.crt:/mosquitto/certificate.pem.crt
      - ./cert/magicbit/private.pem.key:/mosquitto/private.pem.key
    depends_on:
      - influxdb
    networks:
      - iot

  telegraf6:
    image: telegraf
    container_name: telegraf6
    restart: always
    volumes:
      - ./telegrafEpic3.conf:/etc/telegraf/telegraf.conf:ro
      - ./cert/magicbit/AmazonRootCA1.pem:/mosquitto/AmazonRootCA1.pem
      - ./cert/magicbit/certificate.pem.crt:/mosquitto/certificate.pem.crt
      - ./cert/magicbit/private.pem.key:/mosquitto/private.pem.key
    depends_on:
      - influxdb
    networks:
      - iot

  
  grafana:
    image: pdngayan1/grafana:v1
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - iot
    volumes:
#      - ./grafana-provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - influxdb

  keycloak-db:
    image: postgres:latest
    container_name: keycloak-db
    user: root  # needed because windows hates me
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      - iot
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak
    command: start-dev
    depends_on:
      - keycloak-db
    networks:
      - iot
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG: 'true'
      DEBUG_PORT: '*:8787'
      KC_FEATURES: preview

    volumes:
      - kc_data:/opt/keycloak/data

networks:
  iot:

volumes:
  grafana-data:
  influxdb-data:
  influxdb-config:
  keycloak-db:
  kc_data: