{
 "title": "NCINGA Zone wise",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "assertID",
    "label": "Assert ID",
    "query": "All : data_set_MODBUS10, NODEA : data_set_MODBUS13, NODEB : data_set_MODBUS20, NODEC : data_set_MODBUS27, NODED : data_set_MODBUS34,NODEE : data_set_MODBUS41"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Wise Consumption",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS13\",\"data_set_MODBUS20\",\"data_set_MODBUS27\",\"data_set_MODBUS34\",\"data_set_MODBUS41\"]\nzone = [\"data_set_MODBUS13\":\"NODEA\",\"data_set_MODBUS20\":\"NODEB\",\"data_set_MODBUS27\":\"NODEC\",\"data_set_MODBUS34\":\"NODED\",\"data_set_MODBUS41\":\"NODEE\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 100.0}))\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with zone: dict.get(dict: zone, key:r._field, default: \"\"),})) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"zone\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  },
  {
   "title": "Total Energy -${assertID}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value / 100.0}))"
    }
   ]
  },
  {
   "title": "Total Rs. Cost -${assertID}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\") \n  |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value / 100.0}))"
    }
   ]
  },
  {
   "title": "Last Hour Total Power - ${assertID}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value / 100.0}))"
    }
   ]
  },
  {
   "title": "Last 24H Total Power - ${assertID}",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value / 100.0}))"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> filter(fn: (r) => r[\"assertid\"] == \"${assertID:text}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Active Power- ${assertID:text}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\nmodebusid=\"\"\ndata = {\"All\":\"data_set_MODBUS06\",\"NODEA\":\"data_set_MODBUS16\",\"NODEB\":\"data_set_MODBUS23\",\"NODEC\":\"data_set_MODBUS30\",\"NODED\":\"data_set_MODBUS37\",\"NODEE\":\"data_set_MODBUS44\"}\nfrom(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:data[\"${assertID:text}\"]})) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value/ 1000.0 }))\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n "
    }
   ]
  },
  {
   "title": "Daily Current Consumption - ${assertID:text} ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\ndata = {\"All\":\"data_set_MODBUS03\",\"NODEA\":\"data_set_MODBUS14\",\"NODEB\":\"data_set_MODBUS21\",\"NODEC\":\"data_set_MODBUS28\",\"NODED\":\"data_set_MODBUS35\",\"NODEE\":\"data_set_MODBUS42\"}\nfrom(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:data[\"${assertID:text}\"]})) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value / 100.0}))"
    }
   ]
  },
  {
   "title": "Daily Average Voltage - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\ndata = {\"All\":\"data_set_MODBUS00\",\"NODEA\":\"data_set_MODBUS15\",\"NODEB\":\"data_set_MODBUS22\",\"NODEC\":\"data_set_MODBUS29\",\"NODED\":\"data_set_MODBUS36\",\"NODEE\":\"data_set_MODBUS43\"}\nfrom(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:data[\"${assertID:text}\"]})) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid )\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\" then r._value else r._value / 10.0}))"
    }
   ]
  },
  {
   "title": "Power Factor - ${assertID}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\ndata = {\"All\":\"data_set_MODBUS12\",\"NODEA\":\"data_set_MODBUS18\",\"NODEB\":\"data_set_MODBUS25\",\"NODEC\":\"data_set_MODBUS32\",\"NODED\":\"data_set_MODBUS39\",\"NODEE\":\"data_set_MODBUS46\"}\nfrom(bucket: \"NCINGA\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:data[\"${assertID:text}\"]})) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1h, fn: last)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: last)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value / 1000.0}))"
    }
   ]
  },
  {
   "title": "Last 7 Days Energy Consumption   - ${assertID} ",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\ndates =[2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",0:\"Saturday\",1:\"Sunday\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: dates, key:date.weekDay(t: r._time), default: \"\"),\n  })) \n |> drop(columns: [\"modebusid\", \"tag\"])\n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 100.0}))\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Last 7 Days Cost(Rs.)   - ${assertID} ",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\ndates =[2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",0:\"Saturday\",1:\"Sunday\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: dates, key:date.weekDay(t: r._time), default: \"\"),\n  })) \n |> drop(columns: [\"modebusid\", \"tag\"])\n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 100.0}))\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n   |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Last 4 Week Energy Consumption  - ${assertID:text}",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nweeks = [0: \"Week 1\",1: \"Week 2\",2: \"Week 3\",3: \"Week 4\",4: \"Week 5\",5: \"Week 6\",6: \"Week 7\",7: \"Week 8\",8: \"Week 9\",9: \"Week 10\",10: \"Week 11\",11: \"Week 12\",12: \"Week 13\",13: \"Week 14\",14: \"Week 15\",15: \"Week 16\",16: \"Week 17\",17: \"Week 18\",18: \"Week 19\",19: \"Week 20\",20: \"Week 21\",21: \"Week 22\",22: \"Week 23\",23: \"Week 24\",24: \"Week 25\",25: \"Week 26\",26: \"Week 27\",27: \"Week 28\",28: \"Week 29\",29: \"Week 30\",30: \"Week 31\",31: \"Week 32\",32: \"Week 33\",33: \"Week 34\",34: \"Week 35\",35: \"Week 36\",36: \"Week 37\",37: \"Week 38\",38: \"Week 39\",39: \"Week 40\",40: \"Week 41\",41: \"Week 42\",42: \"Week 43\",43: \"Week 44\",44: \"Week 45\",45: \"Week 46\",46: \"Week 47\",47: \"Week 48\",48: \"Week 49\",49: \"Week 50\",50: \"Week 51\",51: \"Week 52\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: weeks, key:date.week(t: r._time), default: \"\"),\n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 1000.0 }))\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Last 4 Week Cost (Rs)  - ${assertID:text}",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nweeks = [0: \"Week 1\",1: \"Week 2\",2: \"Week 3\",3: \"Week 4\",4: \"Week 5\",5: \"Week 6\",6: \"Week 7\",7: \"Week 8\",8: \"Week 9\",9: \"Week 10\",10: \"Week 11\",11: \"Week 12\",12: \"Week 13\",13: \"Week 14\",14: \"Week 15\",15: \"Week 16\",16: \"Week 17\",17: \"Week 18\",18: \"Week 19\",19: \"Week 20\",20: \"Week 21\",21: \"Week 22\",22: \"Week 23\",23: \"Week 24\",24: \"Week 25\",25: \"Week 26\",26: \"Week 27\",27: \"Week 28\",28: \"Week 29\",29: \"Week 30\",30: \"Week 31\",31: \"Week 32\",32: \"Week 33\",33: \"Week 34\",34: \"Week 35\",35: \"Week 36\",36: \"Week 37\",37: \"Week 38\",38: \"Week 39\",39: \"Week 40\",40: \"Week 41\",41: \"Week 42\",42: \"Week 43\",43: \"Week 44\",44: \"Week 45\",45: \"Week 46\",46: \"Week 47\",47: \"Week 48\",48: \"Week 49\",49: \"Week 50\",50: \"Week 51\",51: \"Week 52\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: weeks, key:date.week(t: r._time), default: \"\"),\n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 100.0 }))\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n\n"
    }
   ]
  },
  {
   "title": "Last 12 Month Energy Consumption  - ${assertID}",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -12mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedMonth:\n      dict.get(dict: months, key:date.month(t: r._time), default: \"\"),\n  })) \n  |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedMonth\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 100.0 }))\n |> difference(nonNegative: true)\n|> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Last 12 Month Cost (Rs)  - ${assertID}",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -12mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"${assertID:value}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedMonth:\n      dict.get(dict: months, key:date.month(t: r._time), default: \"\"),\n  })) \n  |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedMonth\"])\n  |> map(fn: (r) => ({r with _value: if \"${assertID:text}\"==\"All\"  then r._value else r._value/ 100.0 }))\n |> difference(nonNegative: true)\n|> sum(column: \"_value\")\n |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n\n |> drop(columns: [\"_value\", \"tag\"])\n\n\n"
    }
   ]
  }
 ]
}