{
 "title": "DEMO Assert Management",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "assertID",
    "label": "Assert ID",
    "query": "from(bucket: \"BLI/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> drop(columns: [\"name\", \"tag\"])\n  |> drop(columns: [\"description\", \"tag\"])\n  |> drop(columns: [\"nodeid\", \"tag\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Assert Registry ",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"BLI/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> filter(fn: (r) => r[\"assertid\"] == \"${assertID}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Active Energy Consumption - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -10h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"]  == \"P\")\n  |> filter(fn: (r) => r[\"device\"] == \"${assertID}\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Daily Current Consumption - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -10h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] == \"i_avg\")\n  |> filter(fn: (r) => r[\"device\"] == \"${assertID}\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Daily Average Voltage - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -10h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] == \"v_avg\")\n  |> filter(fn: (r) => r[\"device\"] == \"${assertID}\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Power Factor - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -10h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] == \"pf\")\n  |> filter(fn: (r) => r[\"device\"] == \"${assertID}\")\n  |> group(columns: [\"device\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n\n\n\n"
    }
   ]
  },
  {
   "title": "Weekly Energy Consumption  ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P\")\n  |> group(columns: [\"device\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Monthly Energy Consumption  ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -365d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] == \"P\")\n  |> group(columns: [\"device\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])"
    }
   ]
  }
 ]
}