{
 "title": "Demo dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "device",
    "query": "from(bucket: \"BLI\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"customer\"])\n  |> distinct(column: \"device\")\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> sort(columns: [\"_value\"], desc: false)\n  |> yield()"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"customer\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Last 24 Hours Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"customer\"])\n  |> sum(column: \"_value\")"
    },
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"BRN/BLI/BLIW12/elec/solar/solar/pf\"\n  )"
    },
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"BRN/BLI/BLIW12/elec/solar/solar/ap_total\"\n  )\n"
    }
   ]
  },
  {
   "title": "Last Hours Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"customer\"])\n  |> sum(column: \"_value\")"
    },
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"BRN/BLI/BLIW12/elec/solar/solar/pf\"\n  )"
    },
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"BRN/BLI/BLIW12/elec/solar/solar/ap_total\"\n  )\n"
    }
   ]
  },
  {
   "title": "Device Wise - Last Hour - Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"BRN/BLI/$device/elec/solar/solar/P\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> group(columns: [\"BRN/BLI/$device/elec/solar/solar/P\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Device Wise -Power Consumption",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> drop(columns: [\"E\", \"tag\"])\n  |> drop(columns: [\"P\", \"tag\"])\n  |> drop(columns: [\"f\", \"tag\"])\n  |> drop(columns: [\"pf\", \"tag\"])\n  |> drop(columns: [\"v_avg\", \"tag\"])\n  |> drop(columns: [\"i_avg\", \"tag\"])\n  |> drop(columns: [\"vA_rms\", \"tag\"])\n  |> drop(columns: [\"vB_rms\", \"tag\"])\n  |> drop(columns: [\"vC_rms\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"ap_total\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"device\"])\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Device Wise -Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"BLI\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"customer\"] == \"BRN\")\n  |> filter(fn: (r) => r[\"group\"] == \"BLI\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /.P/)\n  |> drop(columns: [\"E\", \"tag\"])\n  |> drop(columns: [\"P\", \"tag\"])\n  |> drop(columns: [\"f\", \"tag\"])\n  |> drop(columns: [\"pf\", \"tag\"])\n  |> drop(columns: [\"v_avg\", \"tag\"])\n  |> drop(columns: [\"i_avg\", \"tag\"])\n  |> drop(columns: [\"vA_rms\", \"tag\"])\n  |> drop(columns: [\"vB_rms\", \"tag\"])\n  |> drop(columns: [\"vC_rms\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"ap_total\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> yield()"
    }
   ]
  }
 ]
}