{
 "title": "IFINITY Zone wise",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "assertID",
    "label": "Assert ID",
    "query": "from(bucket: \"IFINITY/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> drop(columns: [\"name\", \"tag\"])\n  |> drop(columns: [\"description\", \"tag\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Node Wise Consumption",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS16\",\"data_set_MODBUS23\",\"data_set_MODBUS30\",\"data_set_MODBUS37\",\"data_set_MODBUS44\"]\nzone = [\"data_set_MODBUS16\":\"NODEA\",\"data_set_MODBUS23\":\"NODEB\",\"data_set_MODBUS30\":\"NODEC\",\"data_set_MODBUS37\":\"NODED\",\"data_set_MODBUS44\":\"NODEE\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 1000.0}))\n  |> sum(column: \"_value\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with \n    zone:\n      dict.get(dict: zone, key:r._field, default: \"\"),\n  })) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> rename(\n        fn: (column) => {\n            _newColumnName = if column =~ /^_/ then \"\" else column\n            return _newColumnName\n        }\n        )"
    }
   ]
  },
  {
   "title": "Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IFINITY\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS06\")\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"]) \n  |> drop(columns: [\"topic\", \"tag\"]) \n  |> drop(columns: [\"_field\", \"tag\"]) \n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Last 24H Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IFINITY\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS06\")\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"]) \n  |> drop(columns: [\"topic\", \"tag\"]) \n  |> drop(columns: [\"_field\", \"tag\"]) \n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Last Hour Total Power Consumption",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IFINITY\")\n  |> range(start: -1h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS06\")\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"]) \n  |> drop(columns: [\"topic\", \"tag\"]) \n  |> drop(columns: [\"_field\", \"tag\"]) \n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Node Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"IFINITY/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> filter(fn: (r) => r[\"assertid\"] == \"${assertID}\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Active Energy/Apparent Consumption - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\nactivePower = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS06\",\"NODEA\":\"MODBUS16\",\"NODEB\":\"MODBUS23\",\"NODEC\":\"MODBUS30\",\"NODED\":\"MODBUS37\",\"NODEE\":\"MODBUS44\"]\nmodebusid=\"\"\nfrom(bucket: \"IFINITY\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with \n    modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: activePower, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n|> drop(columns: [\"modebusid\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Current Consumption - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\ncurrentCons = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS03\",\"NODEA\":\"MODBUS14\",\"NODEB\":\"MODBUS21\",\"NODEC\":\"MODBUS28\",\"NODED\":\"MODBUS35\",\"NODEE\":\"MODBUS42\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n   |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: currentCons, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Average Voltage - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\nvolageAvg = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS00\",\"NODEA\":\"MODBUS15\",\"NODEB\":\"MODBUS22\",\"NODEC\":\"MODBUS29\",\"NODED\":\"MODBUS36\",\"NODEE\":\"MODBUS43\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: volageAvg, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid )\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Power Factor - ${assertID}",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "import \"dict\"\nimport \"strings\"\npowerFact = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS12\",\"NODEA\":\"MODBUS18\",\"NODEB\":\"MODBUS26\",\"NODEC\":\"MODBUS32\",\"NODED\":\"MODBUS39\",\"NODEE\":\"MODBUS46\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: powerFact, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1h, fn: last)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"modebusid\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Energy Consumption  ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\ndates =[2:\"Monday\",3:\"Tuesday\",4:\"Wednesday\",5:\"Thursday\",6:\"Friday\",0:\"Saturday\",1:\"Sunday\"]\nactivePower = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS06\",\"NODEA\":\"MODBUS16\",\"NODEB\":\"MODBUS23\",\"NODEC\":\"MODBUS30\",\"NODED\":\"MODBUS37\",\"NODEE\":\"MODBUS44\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: -7d)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: activePower, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1d, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: dates, key:date.weekDay(t: r._time), default: \"\"),\n  })) \n |> drop(columns: [\"modebusid\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Weekly Energy Consumption  ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nweeks = [0: \"Week 1\",1: \"Week 2\",2: \"Week 3\",3: \"Week 4\",4: \"Week 5\",5: \"Week 6\",6: \"Week 7\",7: \"Week 8\",8: \"Week 9\",9: \"Week 10\",10: \"Week 11\",11: \"Week 12\",12: \"Week 13\",13: \"Week 14\",14: \"Week 15\",15: \"Week 16\",16: \"Week 17\",17: \"Week 18\",18: \"Week 19\",19: \"Week 20\",20: \"Week 21\",21: \"Week 22\",22: \"Week 23\",23: \"Week 24\",24: \"Week 25\",25: \"Week 26\",26: \"Week 27\",27: \"Week 28\",28: \"Week 29\",29: \"Week 30\",30: \"Week 31\",31: \"Week 32\",32: \"Week 33\",33: \"Week 34\",34: \"Week 35\",35: \"Week 36\",36: \"Week 37\",37: \"Week 38\",38: \"Week 39\",39: \"Week 40\",40: \"Week 41\",41: \"Week 42\",42: \"Week 43\",43: \"Week 44\",44: \"Week 45\",45: \"Week 46\",46: \"Week 47\",47: \"Week 48\",48: \"Week 49\",49: \"Week 50\",50: \"Week 51\",51: \"Week 52\"]\nactivePower = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS06\",\"NODEA\":\"MODBUS16\",\"NODEB\":\"MODBUS23\",\"NODEC\":\"MODBUS30\",\"NODED\":\"MODBUS37\",\"NODEE\":\"MODBUS44\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: activePower, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 7d, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: weeks, key:date.week(t: r._time), default: \"\"),\n  })) \n\n"
    }
   ]
  },
  {
   "title": "Mothly Energy Consumption  ",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nmonths = [1:\"January\",2:\"February\",3:\"March\",4:\"April\",5:\"May\",6:\"June\",7:\"July\",8:\"August\",9:\"September\",10:\"October\",11:\"November\",12: \"December\"]\nactivePower = [\"{NODEA,NODEB,NODEC,NODED,NODEE}\":\"MODBUS06\",\"NODEA\":\"MODBUS16\",\"NODEB\":\"MODBUS23\",\"NODEC\":\"MODBUS30\",\"NODED\":\"MODBUS37\",\"NODEE\":\"MODBUS44\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: -12mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> map(fn: (r) => ({ r with modebusid:\"data_set_\"+strings.trim(v:dict.get(dict: activePower, key:\"${assertID}\", default: \"\"),cutset: \"\")  })) \n  |> filter(fn: (r) => r[\"_field\"] == r.modebusid)\n  |> aggregateWindow(every: 1mo, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with \n    namedMonth:\n      dict.get(dict: months, key:date.month(t: r._time), default: \"\"),\n  })) \n  |> drop(columns: [\"_time\", \"tag\"])\n \n\n\n"
    }
   ]
  }
 ]
}