{
 "title": "Overall_nodewise",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "NCINGA - Today Node Wise Consumption",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS13\",\"data_set_MODBUS20\",\"data_set_MODBUS27\",\"data_set_MODBUS34\",\"data_set_MODBUS41\"]\nzone = [\"data_set_MODBUS13\":\"NODEA\",\"data_set_MODBUS20\":\"NODEB\",\"data_set_MODBUS27\":\"NODEC\",\"data_set_MODBUS34\":\"NODED\",\"data_set_MODBUS41\":\"NODEE\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 100.0 }))\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with zone: dict.get(dict: zone, key:r._field, default: \"\"),da:\"Today\"})) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"zone\",\"da\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    },
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS13\",\"data_set_MODBUS20\",\"data_set_MODBUS27\",\"data_set_MODBUS34\",\"data_set_MODBUS41\"]\nzone = [\"data_set_MODBUS13\":\"NODEA\",\"data_set_MODBUS20\":\"NODEB\",\"data_set_MODBUS27\":\"NODEC\",\"data_set_MODBUS34\":\"NODED\",\"data_set_MODBUS41\":\"NODEE\"]\nfrom(bucket: \"NCINGA\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 100.0 }))\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with zone: dict.get(dict: zone, key:r._field, default: \"\"),da:\"Yesterday\"})) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"zone\",\"da\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  },
  {
   "title": "NCINGA Node Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"NCINGA/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> drop(columns: [\"name\", \"tag\"])"
    }
   ]
  },
  {
   "title": "IFINITY - Today Node Wise Consumption",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS13\",\"data_set_MODBUS20\",\"data_set_MODBUS27\",\"data_set_MODBUS34\",\"data_set_MODBUS41\"]\nzone = [\"data_set_MODBUS13\":\"NODEA\",\"data_set_MODBUS20\":\"NODEB\",\"data_set_MODBUS27\":\"NODEC\",\"data_set_MODBUS34\":\"NODED\",\"data_set_MODBUS41\":\"NODEE\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 100.0 }))\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with zone: dict.get(dict: zone, key:r._field, default: \"\"),da:\"Today\"})) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"zone\",\"da\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    },
    {
     "query": "import \"dict\"\nactivePower = [\"data_set_MODBUS13\",\"data_set_MODBUS20\",\"data_set_MODBUS27\",\"data_set_MODBUS34\",\"data_set_MODBUS41\"]\nzone = [\"data_set_MODBUS13\":\"NODEA\",\"data_set_MODBUS20\":\"NODEB\",\"data_set_MODBUS27\":\"NODEC\",\"data_set_MODBUS34\":\"NODED\",\"data_set_MODBUS41\":\"NODEE\"]\nfrom(bucket: \"IFINITY\")\n  |> range(start: -24h)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => contains(set: activePower, value: r._field)) \n  |> map(fn: (r) => ({r with _value: r._value / 100.0 }))\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> map(fn: (r) => ({ r with zone: dict.get(dict: zone, key:r._field, default: \"\"),da:\"Yesterday\"})) \n  |> drop(columns: [\"_field\", \"tag\"])\n  |> group(columns: [\"zone\",\"da\"])\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  },
  {
   "title": "IFINITY Node Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"IFINITY/Master\")\n  |> range(start: -1)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"assert\")\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> drop(columns: [\"name\", \"tag\"])"
    }
   ]
  }
 ]
}