{
 "title": "Overall_Quatly",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Last 4 Week Working / Non-Working ",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nweeks = [0: \"Week 1\",1: \"Week 2\",2: \"Week 3\",3: \"Week 4\",4: \"Week 5\",5: \"Week 6\",6: \"Week 7\",7: \"Week 8\",8: \"Week 9\",9: \"Week 10\",10: \"Week 11\",11: \"Week 12\",12: \"Week 13\",13: \"Week 14\",14: \"Week 15\",15: \"Week 16\",16: \"Week 17\",17: \"Week 18\",18: \"Week 19\",19: \"Week 20\",20: \"Week 21\",21: \"Week 22\",22: \"Week 23\",23: \"Week 24\",24: \"Week 25\",25: \"Week 26\",26: \"Week 27\",27: \"Week 28\",28: \"Week 29\",29: \"Week 30\",30: \"Week 31\",31: \"Week 32\",32: \"Week 33\",33: \"Week 34\",34: \"Week 35\",35: \"Week 36\",36: \"Week 37\",37: \"Week 38\",38: \"Week 39\",39: \"Week 40\",40: \"Week 41\",41: \"Week 42\",42: \"Week 43\",43: \"Week 44\",44: \"Week 45\",45: \"Week 46\",46: \"Week 47\",47: \"Week 48\",48: \"Week 49\",49: \"Week 50\",50: \"Week 51\",51: \"Week 52\"]\nncinga = from(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: weeks, key:date.week(t: r._time), default: \"\"),\n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\",\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n ifinity = from(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    namedDay:\n      dict.get(dict: weeks, key:date.week(t: r._time), default: \"\"),\n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"namedDay\",\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n union(tables: [ncinga, ifinity])\n |> group(columns: [\"namedDay\",\"hourDesc\"])\n |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Last 4 Week Total  Units",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> sum(column: \"_value\")\n|> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n "
    }
   ]
  },
  {
   "title": "Last 4 Week Total  Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\n\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> sum(column: \"_value\")\n  |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n|> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n \n "
    }
   ]
  },
  {
   "title": "Last 4 Week Working / Non-Working ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nncinga = from(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n ifinity = from(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n union(tables: [ncinga, ifinity])\n |> group(columns: [\"hourDesc\"])\n |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  },
  {
   "title": "Last 4 Week Working / Non-Working Costing in (Rs.)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nncinga = from(bucket: \"NCINGA\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n ifinity = from(bucket: \"IFINITY\")\n  |> range(start: -1mo)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> sort(columns: [\"key\"], desc: true)\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with \n    hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\" \n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"   \n      else if (r.hour > 8 and r.hour < 18) then \"Working\"   \n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\" \n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\" \n      else if (r.hour > 23) then \"Non-Working\" \n      else if (r.hour == 0) then \"Non-Working\" \n      else if (r.hour == 6) then \"Setting-Up\" \n      else if (r.hour == 8) then \"Working\" \n      else if (r.hour == 18) then \"Extra-Working\" \n      else if (r.hour == 20) then \"Extra-Working\" \n      else if (r.hour == 23) then \"Non-Working\" else \"-\"  \n  })) \n |> drop(columns: [\"_time\", \"tag\"])\n |> group(columns: [\"hourDesc\"])\n |> difference(nonNegative: true)\n |> sum(column: \"_value\")\n\n\n\n union(tables: [ncinga, ifinity])\n |> group(columns: [\"hourDesc\"])\n |> sum(column: \"_value\")\n      |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n |> drop(columns: [\"_value\", \"tag\"])\n"
    }
   ]
  }
 ]
}