{
 "title": "Overall_Daily",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Today Working / Non-Working ",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour > 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> group(columns: [\"hourDesc\"])\n |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  },
  {
   "title": "Today Total  Units",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> sum(column: \"_value\")\n|> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n "
    }
   ]
  },
  {
   "title": "Today Total  Cost",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_time\", \"tag\"])\n  |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> sum(column: \"_value\")\n   |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n|> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})\n "
    }
   ]
  },
  {
   "title": "Today  Working / Non-Working ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour > 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start:  today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> group(columns: [\"hourDesc\"])\n |> sum(column: \"_value\")\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  },
  {
   "title": "Today Working / Non-Working Costing in (Rs.)",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\nimport \"dict\"\nimport \"strings\"\nimport \"timezone\"\nncinga=from(bucket: \"NCINGA\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour > 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\n\n\n\nifinity=from(bucket: \"IFINITY\")\n  |> range(start: today())\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"_field\"] =~ /data_set/)\n  |> filter(fn: (r) => r[\"_field\"] == \"data_set_MODBUS10\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"host\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> map(fn: (r) => ({ r with  hour: date.hour(t: r._time,location: timezone.location(name: \"Asia/Colombo\"))}))\n  |> map(fn: (r) => ({ r with\n      date:date.monthDay(t: r._time),\n      hourDesc:\n      if (r.hour> 0 and r.hour< 6) then \"Non-Working\"\n      else if (r.hour > 6 and r.hour < 8) then \"Setting-Up\"\n      else if (r.hour > 8 and r.hour < 18) then \"Working\"\n      else if (r.hour > 18 and r.hour < 20) then \"Extra-Working\"\n      else if (r.hour > 20 and r.hour < 23) then \"Non-Working\"\n      else if (r.hour > 23) then \"Non-Working\"\n      else if (r.hour == 0) then \"Non-Working\"\n      else if (r.hour == 6) then \"Setting-Up\"\n      else if (r.hour == 8) then \"Working\"\n      else if (r.hour == 18) then \"Extra-Working\"\n      else if (r.hour == 20) then \"Non-Working\"\n      else if (r.hour == 23) then \"Non-Working\" else \"-\",\n  }))\n  |>sort(columns: [\"date\",\"hour\"])\n  |> difference(nonNegative: true)\n  |> group(columns: [\"hourDesc\",\"hour\"])\n |> sum(column: \"_value\")\n\nunion(tables: [ncinga, ifinity])\n |> group(columns: [\"hourDesc\"])\n |> sum(column: \"_value\")\n     |> map(fn: (r) => ({r with _value: r._value * 65.0}))\n |> rename(fn: (column) => {_newColumnName = if column =~ /^_/ then \"\" else column return _newColumnName})"
    }
   ]
  }
 ]
}