{
 "title": "Deep Pump",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  { "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/255\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((float(v: r._value) - 4.0) / (20.0 - 4.0)) * 204.1/ 60.0 / 1000.0\n     }))\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Daily Water Consumption (m³)\": r._value }))\n  |> keep(columns: [\"_time\", \"Daily Water Consumption (m³)\"])\n"
    }
   ]
  },
  {
   "title": "Hourly Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/255\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (((r._value - 4.0) / (20.0 - 4.0)) * 204.1) / 60.0  \n  }))\n  |> aggregateWindow(\n       every: 1h,\n       fn: mean,\n       createEmpty: true\n  )\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (r._value * 0.5)  \n  }))"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/269\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN4\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((float(v: r._value) - 4.0) / (20.0 - 4.0)) * 459.6/ 60.0 / 1000.0\n     }))\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Daily Water Consumption (m³)\": r._value }))\n  |> keep(columns: [\"_time\", \"Daily Water Consumption (m³)\"])\n"
    }
   ]
  },
  {
   "title": "Daily Consumption ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "import \"date\"\n\nmidnight = date.truncate(t: now(), unit: 1d)\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/269\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN4\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (((r._value - 4.0) / (20.0 - 4.0)) * 204.1) / 60.0  \n  }))\n  |> aggregateWindow(\n       every: 1h,\n       fn: mean,\n       createEmpty: true\n  )\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (r._value * 0.5)  \n  }))"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/255\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> last()\n  |> map(fn: (r) => ({\n       _time: r._time,\n       \"Flow Rate (L/min)\": ((r._value - 4.0) / (20.0 - 4.0)) * 459.6\n     }))\n  |> keep(columns: [\"_time\", \"Flow Rate (L/min)\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/255\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((r._value - 4.0) / (20.0 - 4.0)) * 204.1\n     }))\n  |> aggregateWindow(\n       every: 1m,\n       fn: mean,\n       createEmpty: false\n     )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/269\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN4\")\n  |> last()\n  |> map(fn: (r) => ({\n       _time: r._time,\n       \"Flow Rate (L/min)\": ((r._value - 4.0) / (20.0 - 4.0)) * 459.6\n     }))\n  |> keep(columns: [\"_time\", \"Flow Rate (L/min)\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/269\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN4\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((r._value - 4.0) / (20.0 - 4.0)) * 459.6\n     }))\n  |> aggregateWindow(\n       every: 1m,\n       fn: mean,\n       createEmpty: false\n     )\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 13 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/320\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((float(v: r._value) - 4.0) / (20.0 - 4.0)) * 459.6/ 60.0 / 1000.0\n     }))\n  |> aggregateWindow(every: 1m, fn: sum)\n  |> sum(column: \"_value\")\n  |> map(fn: (r) => ({ _time: r._time, \"Daily Water Consumption (m³)\": r._value }))\n  |> keep(columns: [\"_time\", \"Daily Water Consumption (m³)\"])\n"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/320\")  \n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (((r._value - 4.0) / (20.0 - 4.0)) * 459.6) / 60.0 \n  }))\n  |> aggregateWindow(\n       every: 1h,\n       fn: mean,\n       createEmpty: true\n  )\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: (r._value * 0.5)  \n  }))"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/320\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> last()\n  |> map(fn: (r) => ({\n       _time: r._time,\n       \"Flow Rate (L/min)\": ((r._value - 4.0) / (20.0 - 4.0)) * 459.6\n     }))\n  |> keep(columns: [\"_time\", \"Flow Rate (L/min)\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "import \"date\"\n\nfrom(bucket: \"AHK-AKDL\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"2024/BB/320\")\n  |> filter(fn: (r) => r[\"_field\"] == \"data_AN3\")\n  |> map(fn: (r) => ({\n       _time: r._time,\n       _value: ((r._value - 4.0) / (20.0 - 4.0)) * 459.6\n     }))\n  |> aggregateWindow(\n       every: 1m,\n       fn: mean,\n       createEmpty: false\n     )\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}