{
 "title": "Effluent Treatment Plant - ETP",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305113/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/inlet/flow\")\n    |> drop(columns: [\"host\"])\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n |> map(fn: (r) => ({r with _value: r._value /(3600.0) }))\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305113/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/inlet/flow\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n   |> map(fn: (r) => ({r with _value: r._value /(3600.0) }))\n  |> aggregateWindow(every: 1h, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305114/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/etpout/flow\")\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n     |> map(fn: (r) => ({r with _value: r._value /(3600.0) }))\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305114/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/etpout/flow\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n  |> map(fn: (r) => ({r with _value: r._value /(3600.0) }))\n  |> aggregateWindow(every: 1h, fn: sum)\n"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305113/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/inlet/flow_rate\")\n        |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n\n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305113/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/inlet/flow_rate\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n    |> aggregateWindow(every: 1m, fn: last)  "
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305114/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/etpout/flow_rate\")\n  |> last(column: \"_value\")\n        |> drop(columns: [\"host\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "m3/h" } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305114/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/etpout/flow_rate\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n    |> aggregateWindow(every: 1m, fn: last)  \n"
    }
   ]
  }
 ]
}