{
 "title": "Landing Page",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "\n\n<a href=\"https://www.ncinga.net\" style=\"float:right,back\">\n      <img src=\"https://storage.googleapis.com/ncinga-iot-bucket/impress.png\" alt=\"\"style=\"height:165px;width:300px\">\n  </a>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Electricity Consumption - Gas Gen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "query": "gg1=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN23051/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen1/E\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  gg2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen2/E\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  gg3=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen3/E\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  union(tables: [gg1, gg2, gg3])\n  |> group(columns: [])  // Ungroup data to remove group keys\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Electricity Consumption - REB",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "reb1=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/mreb1/E\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  reb2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/mrebu3/E\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  union(tables: [reb1, reb2])\n  |> group(columns: [])  // Ungroup data to remove group keys\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Steam Distribution - Gas Boiler",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305158/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/random/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Ground Lifting Water",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "dp1=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305102/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/deep1/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  dp2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305103/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/deep2/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  dp3=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305099/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/deep3/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n      union(tables: [dp1, dp2,dp3])\n      |> group(columns: [])  // Ungroup data to remove group keys\n  |>sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Water Consumption - CPB ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "cpb1=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305112/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/cpb1/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  cpb2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305097/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/cpb2/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  cpb3=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305098/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/cpb3/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n      union(tables: [cpb1, cpb2, cpb3])\n      |> group(columns: [])  // Ungroup data to remove group keys\n  |>sum(column: \"_value\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": {
    "content": "\n\n<a href=\"https://iot.ncinga.net/grafana/d/bdaa5bea-518b-4302-82e6-fa8a73ca1d2111/deep-pump?orgId=7&refresh=1m\" style=\"float:right,back\">\n      <img src=\"https://storage.googleapis.com/ncinga-iot-bucket/pozzo-1037556_1920.jpg\" alt=\"\"style=\"height:130px;width:300px\";>\n  </a>\n<h4 style=\"text-align: center;margin-top:10px;font-family:steam-flow-meter?orgId;\"> Deep Pump </h4>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active Power - Gas Gen 1",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN230510/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen1/P\")\n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Active Power - Gas Gen 2",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen2/P\")\n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Active Power - Gas Gen 3",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/main/gen3/P\")\n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Electricity Consumption - Solar",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/mreb1/E\")\n  |> last(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Hourly Electricity Consumption - Solar",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 5 },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/solar/E\")\n  |> keep(columns: [\"_time\", \"_value\"])\n  |> window(every: 1h)\n  |> difference(nonNegative: true)\n  |> sum()\n  |> duplicate(column: \"_stop\", as: \"_time\")\n  |> window(every: inf)\n  |> sort(columns: [\"_time\"])"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 10 },
   "options": {
    "content": "\n\n<a href=\"https://iot.ncinga.net/grafana/d/bdaa5bea-518b-4302-82e6-fa8a73ca1d21114/effluent-treatment-plant-etp?orgId=7&refresh=1m\" style=\"float:right,back\">\n      <img src=\"https://storage.googleapis.com/ncinga-iot-bucket/outlet.png\" alt=\"\"style=\"height:130px;width:300px\";>\n  </a>\n<h4 style=\"text-align: center;margin-top:10px;font-family:steam-flow-meter?orgId;\"> Effluent Treatment Plant</h4>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall Plant Carbon Footprint",
   "type": "canvas",
   "gridPos": { "h": 13, "w": 10, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305105/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"NCING/IMPRESS/INCTL/elec/main/gen2/E\")\n  |> group(columns: [\"customer\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> sum(column: \"_value\")\n     |> map(fn: (r) => ({r with _value: r._value /1000.00 * 0.53/1000.0}))"
    }
   ]
  },
  {
   "title": "Total Water Consumption - Domestic",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "dom1 = from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305108/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/dom1/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n\n  dom2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305106/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/dom2/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])\n\n\nunion(tables: [dom1, dom2])\n  |> group(columns: [])  // Ungroup data to remove group keys\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Total Water Consumption - Dyeing ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "dy1=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305107/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/dyp1/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n  dy2=from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/TN2305109/tx\"  ))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/dyp2/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n\n      union(tables: [dy1, dy2])\n      |> group(columns: [])  // Ungroup data to remove group keys\n  |>sum(column: \"_value\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "options": {
    "content": "\n\n<a href=\"https://iot.ncinga.net/grafana/d/bdaa5bea-518b-4302-82e6-fa8a73ca1d211141/titas-gas-incoimg?orgId=7&refresh=1m\" style=\"float:right,back\">\n      <img src=\"https://storage.googleapis.com/ncinga-iot-bucket/gas3.jpg\" alt=\"\"style=\"height:130px;width:300px\";>\n  </a>\n<h4 style=\"text-align: center;margin-top:10px;font-family:steam-flow-meter?orgId;\"> Titas Gas Incoming </h4>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total ETP Inlet Process Water",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305113/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/inlet/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Total Water Consumption - Dyeing Finishing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305104/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/dyfin/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "options": {
    "content": "\n\n<a href=\"https://iot.ncinga.net/grafana/d/bdaa5bea-518b-4302-82e6-fa8a73ca1d21115/gas-boiler-steam-distribution?orgId=7&refresh=1m\" style=\"float:right,back\">\n      <img src=\"https://storage.googleapis.com/ncinga-iot-bucket/boiler.png\" alt=\"\"style=\"height:130px;width:300px\";>\n  </a>\n<h4 style=\"text-align: center;margin-top:10px;font-family:steam-flow-meter?orgId;\"> Gas Boiler </h4>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total ETP Outlet Process Water",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305114/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/etpout/flow_rate\")\n      |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n  |> drop(columns: [\"host\"])\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Total Water Consumption - Washing",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "m3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"IMPRESS\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => r[\"topic\"] == \"tn/emr/TN2305101/tx\")\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/IMPRESS/INCTL/elec/main/washing/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")"
    }
   ]
  }
 ]
}