{
 "title": "Steam Flow Meter",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "1m",
 "panels": [
  { "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  { "type": "stat", "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  import \"date\"\n\nfrom(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305143/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/stboil/flow_rate\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ton" } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305143/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/stboil/flow_rate\")\n    |> difference(nonNegative: true)\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ton" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "  import \"date\"\n\nfrom(bucket: \"HAMEEM\")\n  |> range(start: date.truncate(t: -1d, unit: 1d))\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305144/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/cwlst1/flow_rate\")\n    |> filter(fn: (r) => r[\"host\"] == \"c800b19c75ef\")\n  |> difference(nonNegative: true)\n  |> sum(column: \"_value\")\n"
    }
   ]
  },
  {
   "title": "Daily Consumption",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ton" } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305144/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/cwlst1/flow_rate\")\n    |> difference(nonNegative: true)\n  |> aggregateWindow(every: 1h, fn: sum)\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ton/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305143/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/stboil/flow_rate\")\n    |> last(column: \"_value\")\n  |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ton/h" } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305143/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/stboil/flow_rate\")\n    |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Current Flow Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ton/h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305144/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/cwlst1/flow_rate\")\n  |> last(column: \"_value\")\n    |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  },
  {
   "title": "Daily Flow Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ton/h" } },
   "targets": [
    {
     "query": "from(bucket: \"HAMEEM\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mqtt_consumer\")\n  |> filter(fn: (r) => (r[\"topic\"] == \"tn/emr/hameem_TN2305144/tx\"))\n  |> filter(fn: (r) => r[\"_field\"] == \"FLOW1_NCING/HAMEEM/CWL/elec/main/cwlst1/flow_rate\")\n    |> drop(columns: [\"_measurement\", \"tag\"])\n  |> drop(columns: [\"_field\", \"tag\"])\n  |> drop(columns: [\"_start\", \"tag\"])\n  |> drop(columns: [\"_stop\", \"tag\"])\n  |> drop(columns: [\"customer\", \"tag\"])\n  |> drop(columns: [\"device\", \"tag\"])\n  |> drop(columns: [\"group\", \"tag\"])\n  |> drop(columns: [\"panel_board\", \"tag\"])\n  |> drop(columns: [\"power_analyze\", \"tag\"])\n  |> drop(columns: [\"topic\", \"tag\"])\n  |> drop(columns: [\"utility_type\", \"tag\"])"
    }
   ]
  }
 ]
}